import * as THREE from 'https://esm.sh/three@0.179.1';
import { OrbitControls } from 'https://esm.sh/three@0.179.1/examples/jsm/controls/OrbitControls.js';
import { EffectComposer } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/UnrealBloomPass.js';
import './styles.css';

const AU = 12;
const PLANETS = [
  { name: 'Mercury', radius: 0.38, distance: 0.39, period: 88, color: '#b9a898', inclination: 7, spin: 0.017, moons: 0 },
  { name: 'Venus', radius: 0.95, distance: 0.72, period: 224.7, color: '#e9c27d', inclination: 3.39, spin: -0.004, moons: 0 },
  { name: 'Earth', radius: 1, distance: 1, period: 365.25, color: '#4aa3ff', inclination: 0, spin: 1, moons: 1 },
  { name: 'Mars', radius: 0.53, distance: 1.52, period: 687, color: '#dd6b4d', inclination: 1.85, spin: 0.97, moons: 2 },
  { name: 'Jupiter', radius: 2.9, distance: 5.2, period: 4332.6, color: '#d4aa78', inclination: 1.3, spin: 2.4, moons: 4 },
  { name: 'Saturn', radius: 2.45, distance: 9.58, period: 10759, color: '#e6d19c', inclination: 2.49, spin: 2.2, moons: 5, ring: true },
  { name: 'Uranus', radius: 1.15, distance: 19.2, period: 30687, color: '#9ee9f2', inclination: 0.77, spin: -1.4, moons: 3, ring: true },
  { name: 'Neptune', radius: 1.1, distance: 30.05, period: 60190, color: '#5277ff', inclination: 1.77, spin: 1.5, moons: 2 },
];
const dom = {
  mount: document.querySelector('#universe'), speed: document.querySelector('#speed'), speedReadout: document.querySelector('#speedReadout'),
  pauseBtn: document.querySelector('#pauseBtn'), resetBtn: document.querySelector('#resetBtn'), focus: document.querySelector('#focus'), date: document.querySelector('#dateReadout'),
  runState: document.querySelector('#runState'), title: document.querySelector('#cardTitle'), text: document.querySelector('#cardText')
};
let speed = Number(dom.speed.value), paused = false, elapsedDays = 0, focus = 'Solar System';
['Solar System', ...PLANETS.map(p => p.name)].forEach(name => dom.focus.add(new Option(name, name)));
function makeTexture(colorA, colorB) { const canvas = document.createElement('canvas'); canvas.width = canvas.height = 128; const ctx = canvas.getContext('2d'); const g = ctx.createRadialGradient(42, 34, 4, 64, 64, 72); g.addColorStop(0, colorA); g.addColorStop(.56, colorB); g.addColorStop(1, '#070912'); ctx.fillStyle = g; ctx.fillRect(0,0,128,128); for (let i=0;i<420;i++){ ctx.globalAlpha=.09; ctx.fillStyle=i%3?'#fff':colorA; ctx.fillRect(Math.random()*128,Math.random()*128,Math.random()*2+.4,Math.random()*8+1);} return new THREE.CanvasTexture(canvas); }
const scene = new THREE.Scene(); scene.fog = new THREE.FogExp2(0x02030a, .0065);
const camera = new THREE.PerspectiveCamera(55, dom.mount.clientWidth/dom.mount.clientHeight, .1, 2200); camera.position.set(0,34,78);
const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' }); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(dom.mount.clientWidth, dom.mount.clientHeight); renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.15; dom.mount.appendChild(renderer.domElement);
const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true; controls.dampingFactor = .055; controls.minDistance = 6; controls.maxDistance = 430;
const composer = new EffectComposer(renderer); composer.addPass(new RenderPass(scene, camera)); composer.addPass(new UnrealBloomPass(new THREE.Vector2(dom.mount.clientWidth, dom.mount.clientHeight), .82, .45, .18));
scene.add(new THREE.AmbientLight(0x68749a, .14)); scene.add(new THREE.PointLight(0xfff3bf, 860, 900, 1.45));
const sun = new THREE.Mesh(new THREE.SphereGeometry(3.4,96,96), new THREE.MeshBasicMaterial({ map: makeTexture('#fff6a8','#ff8b25') })); scene.add(sun);
const corona = new THREE.Mesh(new THREE.SphereGeometry(4.3,96,96), new THREE.MeshBasicMaterial({ color:0xffb347, transparent:true, opacity:.18, blending:THREE.AdditiveBlending })); scene.add(corona);
const starGeo = new THREE.BufferGeometry(); const starCount = 8500; const positions = new Float32Array(starCount*3); const colors = new Float32Array(starCount*3); const palette = ['#fff','#9dc7ff','#ffd6a3','#d7b8ff'].map(c=>new THREE.Color(c));
for (let i=0;i<starCount;i++){ const r=340+Math.random()*780, t=Math.random()*Math.PI*2, ph=Math.acos(2*Math.random()-1); positions[i*3]=r*Math.sin(ph)*Math.cos(t); positions[i*3+1]=r*Math.cos(ph); positions[i*3+2]=r*Math.sin(ph)*Math.sin(t); const c=palette[Math.floor(Math.random()*palette.length)]; colors.set([c.r,c.g,c.b],i*3); }
starGeo.setAttribute('position', new THREE.BufferAttribute(positions,3)); starGeo.setAttribute('color', new THREE.BufferAttribute(colors,3)); const stars = new THREE.Points(starGeo, new THREE.PointsMaterial({ size:1.2, vertexColors:true, transparent:true, opacity:.88 })); scene.add(stars);
const nebula = new THREE.Mesh(new THREE.SphereGeometry(700,64,64), new THREE.MeshBasicMaterial({ color:0x221645, side:THREE.BackSide, transparent:true, opacity:.42 })); scene.add(nebula);
const planetObjects = new Map();
PLANETS.forEach(planet => { const distance = planet.distance*AU; const orbitGroup = new THREE.Group(); orbitGroup.rotation.z = THREE.MathUtils.degToRad(planet.inclination); scene.add(orbitGroup); const orbit = new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(Array.from({length:256},(_,i)=>{ const a=i/256*Math.PI*2; return new THREE.Vector3(Math.cos(a)*distance,0,Math.sin(a)*distance); })), new THREE.LineBasicMaterial({ color:0x6d7da8, transparent:true, opacity:.24 })); orbitGroup.add(orbit); const body = new THREE.Mesh(new THREE.SphereGeometry(Math.max(planet.radius*.75,.26),64,64), new THREE.MeshStandardMaterial({ map:makeTexture('#fff',planet.color), roughness:.72, metalness:.02 })); orbitGroup.add(body); const label = document.createElement('div'); label.className='space-label'; label.textContent=planet.name; dom.mount.appendChild(label); if (planet.ring){ const ring = new THREE.Mesh(new THREE.RingGeometry(planet.radius*1.05, planet.radius*1.75, 96), new THREE.MeshBasicMaterial({ color: planet.name==='Saturn'?0xeed9a8:0x9ee9f2, transparent:true, opacity:.48, side:THREE.DoubleSide })); ring.rotation.x = Math.PI/2.35; body.add(ring); } const moons=[]; for(let i=0;i<planet.moons;i++){ const moon = new THREE.Mesh(new THREE.SphereGeometry(.09+i*.015,24,24), new THREE.MeshStandardMaterial({ color:0xd8dde8, roughness:.8 })); orbitGroup.add(moon); moons.push(moon); } planetObjects.set(planet.name,{ planet, orbitGroup, body, label, moons, seed:Math.random()*Math.PI*2 }); });
function updateHud(){ dom.speedReadout.textContent = `${speed.toLocaleString()} days/sec`; dom.pauseBtn.textContent = paused ? '▶ Resume' : 'Ⅱ Pause'; dom.runState.textContent = paused ? 'Simulation paused' : 'Physics running'; dom.title.textContent = focus; dom.text.textContent = focus==='Solar System' ? 'Drag to orbit, scroll to zoom, and use the HUD to accelerate from human time to sweeping planetary centuries.' : `${focus} is shown with scaled visual size, moons/rings where applicable, and a realistic orbital period relative to Earth.`; }
dom.speed.addEventListener('input', e => { speed = Number(e.target.value); updateHud(); }); document.querySelectorAll('[data-speed]').forEach(b => b.addEventListener('click', () => { speed = Number(b.dataset.speed); dom.speed.value = speed; updateHud(); })); dom.pauseBtn.addEventListener('click', () => { paused = !paused; updateHud(); }); dom.resetBtn.addEventListener('click', () => { elapsedDays = 0; speed = 120; dom.speed.value = speed; updateHud(); }); dom.focus.addEventListener('change', e => { focus = e.target.value; updateHud(); });
const clock = new THREE.Clock(); const projected = new THREE.Vector3();
function animate(){ requestAnimationFrame(animate); const delta=clock.getDelta(); if(!paused) elapsedDays += delta*speed; sun.rotation.y += delta*.08; corona.scale.setScalar(1+Math.sin(performance.now()*.0018)*.025); stars.rotation.y += delta*.002; nebula.rotation.y -= delta*.0008; planetObjects.forEach(obj => { const { planet, orbitGroup, body, label, moons, seed } = obj; const angle = elapsedDays/planet.period*Math.PI*2 + seed; const distance=planet.distance*AU; body.position.set(Math.cos(angle)*distance,0,Math.sin(angle)*distance); body.rotation.y += delta*planet.spin; moons.forEach((moon,i)=>{ const ma=elapsedDays*(.23+i*.08)+i; const md=planet.radius*(1.25+i*.22)+.9; moon.position.set(body.position.x+Math.cos(ma)*md, Math.sin(ma*.8)*.35, body.position.z+Math.sin(ma)*md); }); projected.copy(body.position).applyMatrix4(orbitGroup.matrixWorld).project(camera); label.style.transform = `translate(-50%, -50%) translate(${(projected.x*.5+.5)*dom.mount.clientWidth}px, ${(-projected.y*.5+.5)*dom.mount.clientHeight}px)`; label.style.opacity = projected.z < 1 ? '1' : '0'; }); const selected=planetObjects.get(focus); controls.target.lerp(selected ? selected.body.getWorldPosition(new THREE.Vector3()) : new THREE.Vector3(0,0,0), selected ? .035 : .025); controls.update(); dom.date.textContent = `J2000 + ${Math.round(elapsedDays).toLocaleString()} days`; composer.render(); }
addEventListener('resize', () => { camera.aspect=dom.mount.clientWidth/dom.mount.clientHeight; camera.updateProjectionMatrix(); renderer.setSize(dom.mount.clientWidth,dom.mount.clientHeight); composer.setSize(dom.mount.clientWidth,dom.mount.clientHeight); });
updateHud(); animate();
